version: '3.2'
services:
#  nginx:
#    build:
#      context: .
#      dockerfile: ./docker/nginx/Dockerfile
#      args:
#        - CONFNAME=dev-site.conf
#    ports:
#      - ${DOCKER_PORT:8080}:80
#    depends_on:
#      - php-fpm
  php-fpm:
    tty: true
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - ENVNAME=.env.local
    volumes:
      - .:/app:cached
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_TEST_ROOT_PASSWORD:-secret}
      - MYSQL_DATABASE=${MYSQL_TEST_DATABASE:-kpla-test-db}
      - MYSQL_USER=${MYSQL_TEST_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_TEST_PASSWORD:-secret}
      - TZ='Asia/Tokyo'
    ports:
      - ${MYSQL_PORT:-3307}:3306
